'use strict';

const { createRealtimeRepository } = require('../repositories/realtimeRepository');

function createRealtimeService(dependencies) {
  const { io, cleanText, decodeSocketToken, getUserById, getRoomById, roomPower, publicUser, makeId, now, logError, logModeration } = dependencies;
  const realtimeRepository = createRealtimeRepository(dependencies);
  const voiceRooms = new Map();
  const liveByRoom = new Map();

  function livePublic(live) {
    return { active:true, roomId:live.roomId, sessionId:live.sessionId, hostSocketId:live.hostSocketId, userId:live.hostUserId, displayName:live.hostDisplayName, startedAt:live.startedAt, viewerCount:live.viewers.size, likeCount:live.likes?.size||0, topicTitle:live.topicTitle||'', topicMedia:live.topicMedia||null, topicPlayback:live.topicPlayback||{playing:true,muted:true}, activeSpeakerSocketId:live.activeSpeakerSocketId||'', requestCount:live.guestRequests?.size||0, messages:live.messages||[], broadcasters:[...live.broadcasters.values()].map(b=>({socketId:b.socketId,userId:b.userId,displayName:b.displayName,avatarUrl:b.avatarUrl||'',role:b.role})) };
  }

  function liveViewersPublic(live) {
    return [...live.viewers.values()].map(v=>({ socketId:v.socketId, user:v.user, joinedAt:v.joinedAt }));
  }

  function emitLiveViewers(live) {
    io.to(`live:${live.roomId}`).emit('live:viewers', { roomId:live.roomId, viewers:liveViewersPublic(live) });
  }

  function emitGuestRequests(live) {
    const requests = [...(live.guestRequests || new Map()).values()];
    io.to(live.hostSocketId).emit('live:guest-requests', { roomId:live.roomId, requests });
  }

  function addLiveViewer(live, socketId, user = null) {
    if (!live || socketId === live.hostSocketId) return;
    live.viewers.set(socketId, { socketId, user:user ? publicUser(user) : null, joinedAt:now() });
    io.sockets.sockets.get(socketId)?.join(`live:${live.roomId}`);
    for (const broadcasterSocket of live.broadcasters.keys()) {
      if (broadcasterSocket !== socketId) io.to(broadcasterSocket).emit('live:viewer', { viewerSocketId:socketId, roomId:live.roomId });
    }
    io.to(socketId).emit('live:status', livePublic(live));
    io.to(`room:${live.roomId}`).emit('live:status', livePublic(live));
    emitLiveViewers(live);
  }

  async function socketUser(socket, token) {
    const decoded=decodeSocketToken(token); if(!decoded) return null;
    const user=await getUserById(decoded.id); if(!user||user.status!=='active') return null;
    socket.data.userId=user.id; socket.data.user=user; return user;
  }

  function sameUser(a, b) {
    return !!a && !!b && String(a) === String(b);
  }

  async function liveHostActor(socket, token, live) {
    const actor = token ? await socketUser(socket, token) : null;
    if (sameUser(actor?.id, live?.hostUserId)) return actor;
    const sessionUser = socket.data.user || (socket.data.userId ? await getUserById(socket.data.userId) : null);
    if (sessionUser?.status === 'active' && sameUser(sessionUser.id, live?.hostUserId)) return sessionUser;
    if (socket.id === live?.hostSocketId) {
      const host = await getUserById(live.hostUserId);
      if (host?.status === 'active') {
        socket.data.userId = host.id;
        socket.data.user = host;
        return host;
      }
    }
    return null;
  }

  function emitVoiceState(roomId) {
    const state=voiceRooms.get(roomId); const participants=state?[...state.participants.values()].map(p=>({socketId:p.socketId,user:p.user,role:p.role,muted:!!p.muted})):[];
    io.to(`voice:${roomId}`).emit('voice:participants',{roomId,participants});
    io.to(`room:${roomId}`).emit('voice:count',{roomId,count:participants.length});
  }

  function removeSocketFromRtc(socket) {
    for (const [roomId,state] of voiceRooms) {
      state.monitors?.delete(socket.id);
      if(state.participants.delete(socket.id)){
        socket.to(`voice:${roomId}`).emit('voice:user-left',{socketId:socket.id});
        if(!state.participants.size && !(state.monitors?.size)) voiceRooms.delete(roomId);
        emitVoiceState(roomId);
      } else if(!state.participants.size && !(state.monitors?.size)) voiceRooms.delete(roomId);
    }
    for (const [roomId,live] of liveByRoom) {
      const wasViewer = live.viewers.delete(socket.id);
      if(live.monitors?.delete(socket.id)) for(const b of live.broadcasters.keys()) io.to(b).emit('live:viewer-left',{viewerSocketId:socket.id,roomId});
      if(socket.id===live.hostSocketId){
        liveByRoom.delete(roomId); io.emit('rooms:live-status',{roomId,active:false}); io.to(`room:${roomId}`).emit('live:ended',{roomId,forced:false}); io.to(`live:${roomId}`).emit('live:ended',{roomId,forced:false});
      } else if(live.broadcasters.has(socket.id)) {
        live.broadcasters.delete(socket.id); io.to(`live:${roomId}`).emit('live:broadcaster-removed',{roomId,socketId:socket.id}); io.to(`room:${roomId}`).emit('live:status',livePublic(live));
      } else {
        for(const b of live.broadcasters.keys()) io.to(b).emit('live:viewer-left',{viewerSocketId:socket.id,roomId});
      }
      if(wasViewer)emitLiveViewers(live);
    }
  }

  function registerHandlers() {
    io.on('connection', socket => {
      socket.on('session:auth', async p=>{try{const u=await socketUser(socket,p?.token);if(u)socket.join(`user:${u.id}`);socket.emit('session:auth-result',{ok:!!u,user:u?publicUser(u):null})}catch(e){logError(e,'session:auth')}});
      socket.on('room:join', async roomId => {try{const room=await getRoomById(cleanText(roomId,40));if(!room)return;for(const r of socket.rooms)if(String(r).startsWith('room:'))socket.leave(r);socket.join(`room:${room.id}`);const live=liveByRoom.get(room.id);socket.emit('live:status',live?livePublic(live):{active:false,roomId:room.id});if(live){io.to(live.hostSocketId).emit('live:invite-candidates-changed',{roomId:room.id});if(socket.data.userId===live.hostUserId)emitGuestRequests(live);}const state=voiceRooms.get(room.id);socket.emit('voice:count',{roomId:room.id,count:state?.participants.size||0});}catch(e){logError(e,'room:join')}});
      socket.on('live:status-request',p=>{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);socket.emit('live:status',live?livePublic(live):{active:false,roomId})});
      socket.on('room:message', async p=>{try{const user=await socketUser(socket,p?.token);const roomId=cleanText(p?.roomId,40),text=cleanText(p?.text,1000);const room=await getRoomById(roomId);if(!user||!room||!text)return;const power=await roomPower(user.id,room);if(power.banned)return socket.emit('room:error',{error:'تم حجبك من هذه الغرفة'});if((room.status||'active')!=='active')return socket.emit('room:error',{error:'الغرفة مغلقة حاليًا'});const m={id:makeId('m'),roomId,userId:user.id,text,createdAt:now()};await realtimeRepository.createRoomMessage(m);io.to(`room:${roomId}`).emit('room:message',{...m,author:publicUser(user)})}catch(e){logError(e,'room:message')}});
      socket.on('live:message', async p=>{try{const user=await socketUser(socket,p?.token);const roomId=cleanText(p?.roomId,40),text=cleanText(p?.text,1000),live=liveByRoom.get(roomId),room=await getRoomById(roomId);if(!user||!room||!live||!text)return;const power=await roomPower(user.id,room);if(power.banned)return socket.emit('live:error',{error:'تم حجبك من هذه الغرفة'});if((room.status||'active')!=='active')return socket.emit('live:error',{error:'الغرفة مغلقة'});const m={id:makeId('lm'),roomId,sessionId:live.sessionId,userId:user.id,text,createdAt:now(),author:publicUser(user)};live.messages=live.messages||[];live.messages.push(m);if(live.messages.length>300)live.messages=live.messages.slice(-300);io.to(`live:${roomId}`).to(`room:${roomId}`).emit('live:message',m)}catch(e){logError(e,'live:message')}});
      socket.on('live:like',async p=>{try{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId),room=await getRoomById(roomId);if(!live||!room)return;const user=p?.token?await socketUser(socket,p.token):socket.data.user||null;if(user){const power=await roomPower(user.id,room);if(power.banned)return socket.emit('live:error',{error:'تم حجبك من هذه الغرفة'});}if(!live.likes)live.likes=new Set();const key=user?`u:${user.id}`:`s:${socket.id}`;const liked=!live.likes.has(key);if(liked)live.likes.add(key);else live.likes.delete(key);const payload={roomId,likeCount:live.likes.size,liked};socket.emit('live:like-result',payload);io.to(`live:${roomId}`).emit('live:likes',{roomId,likeCount:live.likes.size});io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:like')}});
      socket.on('live:title',async p=>{try{const actor=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!actor||!live||live.hostUserId!==actor.id)return;live.topicTitle=cleanText(p?.title,120);const payload=livePublic(live);io.to(`live:${roomId}`).emit('live:title',{roomId,title:live.topicTitle});io.to(`room:${roomId}`).emit('live:status',payload);io.emit('rooms:live-status',{roomId,active:true,live:payload})}catch(e){logError(e,'live:title')}});
      socket.on('live:topic-control',async p=>{try{const actor=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!actor||!live||live.hostUserId!==actor.id)return;live.topicPlayback={playing:p?.playing!==false,muted:p?.muted!==false};io.to(`live:${roomId}`).emit('live:topic-control',{roomId,playback:live.topicPlayback});io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:topic-control')}});
      socket.on('live:speaker',async p=>{try{const actor=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),socketId=cleanText(p?.socketId,80),live=liveByRoom.get(roomId);if(!actor||!live||live.hostUserId!==actor.id)return;if(socketId&&!live.broadcasters.has(socketId))return;live.activeSpeakerSocketId=socketId;io.to(`live:${roomId}`).emit('live:speaker',{roomId,socketId});io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:speaker')}});
      socket.on('live:guest-request',async p=>{try{const user=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId),room=await getRoomById(roomId);if(!user||!live||!room)return;const power=await roomPower(user.id,room);if(power.banned)return socket.emit('live:error',{error:'تم حجبك من هذه الغرفة'});if(live.broadcasters.has(socket.id))return;if(!live.guestRequests)live.guestRequests=new Map();const request={socketId:socket.id,user:publicUser(user),createdAt:now()};live.guestRequests.set(socket.id,request);socket.emit('live:guest-request-result',{roomId,ok:true});emitGuestRequests(live);io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:guest-request')}});

      socket.on('voice:join', async p=>{try{const user=await socketUser(socket,p?.token);const roomId=cleanText(p?.roomId,40),room=await getRoomById(roomId);if(!user||!room)return socket.emit('voice:error',{error:'يلزم تسجيل الدخول'});const power=await roomPower(user.id,room);if(power.banned)return socket.emit('voice:error',{error:'تم حجبك من هذه الغرفة'});if((room.status||'active')!=='active')return socket.emit('voice:error',{error:'الغرفة مغلقة'});if(!voiceRooms.has(roomId))voiceRooms.set(roomId,{participants:new Map(),monitors:new Set()});const state=voiceRooms.get(roomId);const peers=[...state.participants.keys()];const role=power.role==='guest'?'member':power.role;state.participants.set(socket.id,{socketId:socket.id,user:publicUser(user),role,muted:false});socket.join(`voice:${roomId}`);socket.emit('voice:peers',{roomId,peers});socket.to(`voice:${roomId}`).emit('voice:user-joined',{socketId:socket.id,user:publicUser(user),role});for(const monitorId of state.monitors||[])socket.emit('voice:monitor-peer',{roomId,monitorSocketId:monitorId});emitVoiceState(roomId)}catch(e){logError(e,'voice:join')}});
      socket.on('voice:leave',p=>{const roomId=cleanText(p?.roomId,40),state=voiceRooms.get(roomId);if(!state)return;state.participants.delete(socket.id);socket.leave(`voice:${roomId}`);socket.to(`voice:${roomId}`).emit('voice:user-left',{socketId:socket.id});if(!state.participants.size && !(state.monitors?.size))voiceRooms.delete(roomId);emitVoiceState(roomId)});
      socket.on('voice:moderate', async p=>{try{const actor=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80),action=cleanText(p?.action,20),room=await getRoomById(roomId),state=voiceRooms.get(roomId);if(!actor||!room||!state)return;const power=await roomPower(actor.id,room);if(!power.canModerate)return socket.emit('voice:error',{error:'ليست لديك صلاحية إدارة المتحدثين'});const target=state.participants.get(targetSocketId);if(!target)return;if(action==='mute'){target.muted=true;io.to(targetSocketId).emit('voice:force-mute',{roomId,by:actor.id});await logModeration(actor.id,'voice_mute','user',target.user.id,roomId,{})}else if(action==='kick'){state.participants.delete(targetSocketId);io.to(targetSocketId).emit('voice:kicked',{roomId,reason:'تم إخراجك من الغرفة الصوتية'});io.sockets.sockets.get(targetSocketId)?.leave(`voice:${roomId}`);io.to(`voice:${roomId}`).emit('voice:user-left',{socketId:targetSocketId});await logModeration(actor.id,'voice_kick','user',target.user.id,roomId,{})}emitVoiceState(roomId)}catch(e){logError(e,'voice:moderate')}});
      socket.on('admin:voice-monitor', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40);if(!admin||admin.role!=='admin')return;let state=voiceRooms.get(roomId);if(!state){state={participants:new Map(),monitors:new Set()};voiceRooms.set(roomId,state)}if(!state.monitors)state.monitors=new Set();state.monitors.add(socket.id);socket.data.adminVoiceMonitorRoom=roomId;for(const peerId of state.participants.keys())io.to(peerId).emit('voice:monitor-peer',{roomId,monitorSocketId:socket.id});socket.emit('admin:voice-monitor-ready',{roomId,count:state.participants.size})}catch(e){logError(e,'admin:voice-monitor')}});
      socket.on('admin:voice-unmonitor', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40);if(!admin||admin.role!=='admin')return;const state=voiceRooms.get(roomId);state?.monitors?.delete(socket.id);if(state&&!state.participants.size&&!state.monitors.size)voiceRooms.delete(roomId);socket.data.adminVoiceMonitorRoom=null}catch(e){logError(e,'admin:voice-unmonitor')}});

      socket.on('rtc:offer',p=>p?.to&&io.to(p.to).emit('rtc:offer',{from:socket.id,sdp:p.sdp,kind:p.kind,roomId:p.roomId}));
      socket.on('rtc:answer',p=>p?.to&&io.to(p.to).emit('rtc:answer',{from:socket.id,sdp:p.sdp,kind:p.kind,roomId:p.roomId}));
      socket.on('rtc:ice',p=>p?.to&&io.to(p.to).emit('rtc:ice',{from:socket.id,candidate:p.candidate,kind:p.kind,roomId:p.roomId}));

      socket.on('live:start', async p=>{try{const user=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),room=await getRoomById(roomId);if(!user||!room)return socket.emit('live:error',{error:'يلزم تسجيل الدخول'});const power=await roomPower(user.id,room);if(power.banned)return socket.emit('live:error',{error:'تم حجبك من الغرفة'});if((room.status||'active')!=='active')return socket.emit('live:error',{error:'الغرفة مغلقة'});if(liveByRoom.has(roomId))return socket.emit('live:error',{error:'يوجد بث مباشر قائم في هذه الغرفة'});const live={roomId,sessionId:makeId('live'),hostSocketId:socket.id,hostUserId:user.id,hostDisplayName:user.displayName||user.username,startedAt:now(),topicTitle:cleanText(p?.title,120),topicMedia:null,topicPlayback:{playing:true,muted:false},activeSpeakerSocketId:socket.id,messages:[],likes:new Set(),broadcasters:new Map(),viewers:new Map(),monitors:new Set(),invitedUsers:new Set(),guestRequests:new Map()};live.broadcasters.set(socket.id,{socketId:socket.id,userId:user.id,displayName:user.displayName||user.username,avatarUrl:user.avatarUrl||'',role:'host'});liveByRoom.set(roomId,live);socket.join(`room:${roomId}`);socket.join(`live:${roomId}`);io.emit('rooms:live-status',{roomId,active:true,live:livePublic(live)});io.to(`room:${roomId}`).emit('live:started',livePublic(live));io.to(`live:${roomId}`).emit('live:status',livePublic(live));emitLiveViewers(live)}catch(e){logError(e,'live:start')}});
      socket.on('live:watch',async p=>{try{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId),room=await getRoomById(roomId);if(!live||!room)return socket.emit('live:status',{active:false,roomId});const user=p?.token?await socketUser(socket,p.token):socket.data.user||null;if(user){const power=await roomPower(user.id,room);if(power.banned)return socket.emit('live:error',{error:'تم حجبك من هذه الغرفة'});}const speaker=live.broadcasters.get(socket.id);if(speaker?.role==='guest'){live.broadcasters.delete(socket.id);io.to(`live:${roomId}`).emit('live:broadcaster-removed',{roomId,socketId:socket.id});}addLiveViewer(live,socket.id,user)}catch(e){logError(e,'live:watch')}});
      socket.on('live:unwatch',p=>{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);socket.leave(`live:${roomId}`);if(live){const wasViewer=live.viewers.delete(socket.id);for(const b of live.broadcasters.keys())io.to(b).emit('live:viewer-left',{viewerSocketId:socket.id,roomId});if(wasViewer){io.to(`room:${roomId}`).emit('live:status',livePublic(live));emitLiveViewers(live)}}});
      socket.on('live:viewer-remove',async p=>{try{const actor=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80),live=liveByRoom.get(roomId);if(!actor||!live||live.hostUserId!==actor.id)return;const target=live.viewers.get(targetSocketId);if(!target)return;live.viewers.delete(targetSocketId);io.to(targetSocketId).emit('live:viewer-removed',{roomId,reason:'تم إخراجك من البث'});io.sockets.sockets.get(targetSocketId)?.leave(`live:${roomId}`);for(const b of live.broadcasters.keys())io.to(b).emit('live:viewer-left',{viewerSocketId:targetSocketId,roomId});io.to(`room:${roomId}`).emit('live:status',livePublic(live));emitLiveViewers(live);await logModeration(actor.id,'live_viewer_remove',target.user?'user':'live_viewer',target.user?.id||targetSocketId,roomId,{sessionId:live.sessionId})}catch(e){logError(e,'live:viewer-remove')}});
      socket.on('live:viewer-ban',async p=>{try{const actor=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80),live=liveByRoom.get(roomId),room=await getRoomById(roomId);if(!actor||!live||!room||live.hostUserId!==actor.id)return;const target=live.viewers.get(targetSocketId);if(!target?.user?.id)return socket.emit('live:error',{error:'يمكن حظر المشاهدين المسجلين فقط'});await realtimeRepository.banRoomUser({id:makeId('rm'),roomId,userId:target.user.id,createdAt:now()});live.viewers.delete(targetSocketId);io.to(targetSocketId).emit('live:viewer-removed',{roomId,reason:'تم حظرك من هذه الساحة'});io.sockets.sockets.get(targetSocketId)?.leave(`live:${roomId}`);io.sockets.sockets.get(targetSocketId)?.leave(`room:${roomId}`);for(const b of live.broadcasters.keys())io.to(b).emit('live:viewer-left',{viewerSocketId:targetSocketId,roomId});io.to(`room:${roomId}`).emit('room:user-banned',{roomId,userId:target.user.id});io.to(`room:${roomId}`).emit('live:status',livePublic(live));emitLiveViewers(live);await logModeration(actor.id,'live_viewer_ban','user',target.user.id,roomId,{sessionId:live.sessionId})}catch(e){logError(e,'live:viewer-ban')}});
      socket.on('live:invite-candidates', async p=>{try{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId),actor=live?await liveHostActor(socket,p?.token,live):null;if(!actor||!live)return socket.emit('live:invite-candidates',{roomId,users:[]});const broadcasterUsers=new Set([...live.broadcasters.values()].map(b=>b.userId));const users=new Map();for(const v of live.viewers.values())if(v.user?.id&&v.user.id!==actor.id&&!broadcasterUsers.has(v.user.id))users.set(v.socketId,{...v.user,socketId:v.socketId});for(const s of io.sockets.sockets.values()){const user=s.data.user;if(!user||user.id===actor.id||broadcasterUsers.has(user.id)||(!s.rooms.has(`room:${roomId}`)&&!s.rooms.has(`live:${roomId}`)))continue;users.set(user.id,{...publicUser(user),socketId:s.id});}socket.emit('live:invite-candidates',{roomId,users:[...users.values()]})}catch(e){logError(e,'live:invite-candidates')}});
      socket.on('live:invite', async p=>{try{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId),actor=live?await liveHostActor(socket,p?.token,live):null;if(!actor||!live)return socket.emit('live:error',{error:'صاحب البث فقط يستطيع دعوة ضيف'});let targetUserId=cleanText(p?.targetUserId,80),targetSocketId=cleanText(p?.targetSocketId,80);if(!targetUserId&&targetSocketId)targetUserId=live.viewers.get(targetSocketId)?.user?.id||io.sockets.sockets.get(targetSocketId)?.data.userId||'';if(!targetUserId&&p?.username)targetUserId=await realtimeRepository.findUserIdByUsername(cleanText(p.username,24));if(!targetUserId)return socket.emit('live:error',{error:'المستخدم غير موجود'});if(targetUserId===actor.id)return socket.emit('live:error',{error:'أنت بالفعل صاحب البث'});live.invitedUsers.add(targetUserId);let sent=false;const invitePayload={roomId,sessionId:live.sessionId,from:{userId:actor.id,displayName:actor.displayName||actor.username}};if(targetSocketId){const targetSocket=io.sockets.sockets.get(targetSocketId);if(targetSocket&&(targetSocket.rooms.has(`room:${roomId}`)||targetSocket.rooms.has(`live:${roomId}`))){targetSocket.emit('live:invite',invitePayload);sent=true}}for(const s of io.sockets.sockets.values())if(s.data.userId===targetUserId&&(s.rooms.has(`room:${roomId}`)||s.rooms.has(`live:${roomId}`))){s.emit('live:invite',invitePayload);sent=true}socket.emit('live:invite-result',{ok:sent,targetUserId,targetSocketId});await logModeration(actor.id,'live_invite','user',targetUserId,roomId,{sessionId:live.sessionId,targetSocketId})}catch(e){logError(e,'live:invite')}});
      socket.on('live:guest-request-approve', async p=>{try{const roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.socketId,80),live=liveByRoom.get(roomId),actor=live?await liveHostActor(socket,p?.token,live):null;if(!actor||!live)return;const request=live.guestRequests?.get(targetSocketId);if(!request?.user?.id)return;live.guestRequests.delete(targetSocketId);live.invitedUsers.add(request.user.id);io.to(targetSocketId).emit('live:invite',{roomId,sessionId:live.sessionId,from:{userId:actor.id,displayName:actor.displayName||actor.username}});emitGuestRequests(live);io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:guest-request-approve')}});
      socket.on('live:guest-request-decline', async p=>{try{const roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.socketId,80),live=liveByRoom.get(roomId),actor=live?await liveHostActor(socket,p?.token,live):null;if(!actor||!live)return;live.guestRequests?.delete(targetSocketId);io.to(targetSocketId).emit('live:guest-request-result',{roomId,ok:false});emitGuestRequests(live);io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:guest-request-decline')}});
      socket.on('live:guest-accept', async p=>{try{const user=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!user||!live||!live.invitedUsers.has(user.id))return socket.emit('live:error',{error:'لا توجد دعوة صالحة لهذا البث'});live.invitedUsers.delete(user.id);live.guestRequests?.delete(socket.id);live.viewers.delete(socket.id);socket.join(`live:${roomId}`);const existingBroadcasters=[...live.broadcasters.keys()].filter(id=>id!==socket.id);live.broadcasters.set(socket.id,{socketId:socket.id,userId:user.id,displayName:user.displayName||user.username,avatarUrl:user.avatarUrl||'',role:'guest'});for(const viewer of [...live.viewers.keys(),...(live.monitors||[])])if(viewer!==socket.id)io.to(socket.id).emit('live:viewer',{viewerSocketId:viewer,roomId});for(const broadcasterSocket of existingBroadcasters)io.to(broadcasterSocket).emit('live:viewer',{viewerSocketId:socket.id,roomId});const broadcaster={socketId:socket.id,userId:user.id,displayName:user.displayName||user.username,avatarUrl:user.avatarUrl||'',role:'guest'};io.to(`live:${roomId}`).emit('live:broadcaster-added',{roomId,broadcaster});io.to(`room:${roomId}`).emit('live:status',livePublic(live));emitGuestRequests(live);emitLiveViewers(live)}catch(e){logError(e,'live:guest-accept')}});
      socket.on('live:guest-leave', async p=>{try{const user=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!user||!live)return;const target=live.broadcasters.get(socket.id);if(!target||target.role!=='guest')return;live.broadcasters.delete(socket.id);socket.leave(`live:${roomId}`);io.to(`live:${roomId}`).emit('live:broadcaster-removed',{roomId,socketId:socket.id});for(const b of live.broadcasters.keys())io.to(b).emit('live:viewer-left',{viewerSocketId:socket.id,roomId});io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:guest-leave')}});
      socket.on('live:guest-remove', async p=>{try{const roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80),live=liveByRoom.get(roomId),actor=live?await liveHostActor(socket,p?.token,live):null;if(!actor||!live)return;const target=live.broadcasters.get(targetSocketId);if(!target||target.role==='host')return;live.broadcasters.delete(targetSocketId);const targetUser=await getUserById(target.userId);io.to(targetSocketId).emit('live:guest-removed',{roomId,reason:'أنهى صاحب البث مشاركتك'});io.to(`live:${roomId}`).emit('live:broadcaster-removed',{roomId,socketId:targetSocketId});addLiveViewer(live,targetSocketId,targetUser);await logModeration(actor.id,'live_guest_remove','user',target.userId,roomId,{sessionId:live.sessionId});io.to(`room:${roomId}`).emit('live:status',livePublic(live))}catch(e){logError(e,'live:guest-remove')}});
      socket.on('live:broadcaster-mute', async p=>{try{const roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80),live=liveByRoom.get(roomId),actor=live?await liveHostActor(socket,p?.token,live):null;if(!actor||!live)return;const target=live.broadcasters.get(targetSocketId);if(!target||target.role==='host')return;io.to(targetSocketId).emit('live:force-mute',{roomId,reason:'تم كتم صوتك بواسطة مضيف البث'});await logModeration(actor.id,'live_guest_mute','user',target.userId,roomId,{sessionId:live.sessionId})}catch(e){logError(e,'live:broadcaster-mute')}});
      socket.on('live:stop',p=>{const roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!live||live.hostSocketId!==socket.id)return;liveByRoom.delete(roomId);io.emit('rooms:live-status',{roomId,active:false});io.to(`room:${roomId}`).emit('live:ended',{roomId});io.to(`live:${roomId}`).emit('live:ended',{roomId})});

      socket.on('admin:live-monitor', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!admin||admin.role!=='admin'||!live)return socket.emit('admin:live-monitor-ready',{roomId,active:false});if(!live.monitors)live.monitors=new Set();live.monitors.add(socket.id);socket.data.adminLiveMonitorRoom=roomId;for(const broadcasterSocket of live.broadcasters.keys())if(broadcasterSocket!==socket.id)io.to(broadcasterSocket).emit('live:viewer',{viewerSocketId:socket.id,roomId});socket.emit('admin:live-monitor-ready',{roomId,active:true,broadcasters:livePublic(live).broadcasters})}catch(e){logError(e,'admin:live-monitor')}});
      socket.on('admin:live-unmonitor', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),live=liveByRoom.get(roomId);if(!admin||admin.role!=='admin')return;if(live?.monitors?.delete(socket.id))for(const b of live.broadcasters.keys())io.to(b).emit('live:viewer-left',{viewerSocketId:socket.id,roomId});socket.data.adminLiveMonitorRoom=null}catch(e){logError(e,'admin:live-unmonitor')}});
      socket.on('admin:live-stop', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40);if(!admin||admin.role!=='admin')return;const live=liveByRoom.get(roomId);if(!live)return;liveByRoom.delete(roomId);io.emit('rooms:live-status',{roomId,active:false});io.to(`live:${roomId}`).emit('live:force-ended',{roomId,reason:'انتهى البث المباشر'});io.to(`room:${roomId}`).emit('live:ended',{roomId,forced:true});await logModeration(admin.id,'admin_live_stop','live',live.sessionId,roomId,{})}catch(e){logError(e,'admin:live-stop')}});
      socket.on('admin:live-guest-remove', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80);if(!admin||admin.role!=='admin')return;const live=liveByRoom.get(roomId),target=live?.broadcasters.get(targetSocketId);if(!live||!target||target.role==='host')return;live.broadcasters.delete(targetSocketId);const targetUser=await getUserById(target.userId);io.to(targetSocketId).emit('live:guest-removed',{roomId,reason:'تم إنهاء مشاركتك'});io.to(`live:${roomId}`).emit('live:broadcaster-removed',{roomId,socketId:targetSocketId});addLiveViewer(live,targetSocketId,targetUser);io.to(`room:${roomId}`).emit('live:status',livePublic(live));await logModeration(admin.id,'admin_live_guest_remove','user',target.userId,roomId,{sessionId:live.sessionId})}catch(e){logError(e,'admin:live-guest-remove')}});
      socket.on('admin:voice-kick', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80);if(!admin||admin.role!=='admin')return;const state=voiceRooms.get(roomId),target=state?.participants.get(targetSocketId);if(!target)return;state.participants.delete(targetSocketId);io.to(targetSocketId).emit('voice:kicked',{roomId,reason:'تم إخراجك من الغرفة الصوتية'});io.sockets.sockets.get(targetSocketId)?.leave(`voice:${roomId}`);emitVoiceState(roomId);await logModeration(admin.id,'admin_voice_kick','user',target.user.id,roomId,{})}catch(e){logError(e,'admin:voice-kick')}});
      socket.on('admin:voice-mute', async p=>{try{const admin=await socketUser(socket,p?.token),roomId=cleanText(p?.roomId,40),targetSocketId=cleanText(p?.targetSocketId,80);if(!admin||admin.role!=='admin')return;const state=voiceRooms.get(roomId),target=state?.participants.get(targetSocketId);if(!target)return;target.muted=true;io.to(targetSocketId).emit('voice:force-mute',{roomId,by:'admin'});emitVoiceState(roomId);await logModeration(admin.id,'admin_voice_mute','user',target.user.id,roomId,{})}catch(e){logError(e,'admin:voice-mute')}});
      socket.on('disconnect',()=>removeSocketFromRtc(socket));
    });
  }

  return { voiceRooms, liveByRoom, livePublic, registerHandlers };
}

module.exports = { createRealtimeService };
